stages:
  prepare:
    cmd: python src/prepare.py data/raw/House_Rent_10M_balanced_40cities.csv data/prepared
    deps:
      - data/raw/House_Rent_10M_balanced_40cities.csv
      - src/prepare.py
    outs:
      - data/prepared

  train:
    cmd: python src/train.py data/prepared data/models --n_estimators 100 --max_depth 10 --random_state 365
    deps:
      - data/prepared
      - src/train.py
      - src/utils.py
    outs:
      - data/models

  optimize:
    cmd: python src/optimize.py
    deps:
      - src/optimize.py
      - config/
      - data/prepared
    outs:
      - models/best_model.pkl
